build site:
  image: node:latest
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - rsync -rav --delete dist/ root@nginx.hel.local:/var/www/domiibunn.live
